/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class', // Enable dark mode with 'dark' class on <html>
  theme: {
    extend: {
      colors: {
        // Use CSS variables generated by backend (/api/theme.css)
        // These variables automatically switch between light/dark via :root.dark
        // Fallback to hardcoded values if CSS variables are not available
        primary: 'var(--color-primary, #FECC00)',
        secondary: 'var(--color-secondary, #1F2937)',
        accent: 'var(--color-accent, #3B82F6)',
        background: 'var(--color-background, #F9FAFB)',
        surface: 'var(--color-surface, #FFFFFF)',
        'text-primary': 'var(--color-text-primary, #111827)',
        'text-secondary': 'var(--color-text-secondary, #6B7280)',
        success: 'var(--color-success, #10B981)',
        error: 'var(--color-error, #EF4444)',
      },
      fontFamily: {
        primary: 'var(--font-primary, system-ui, sans-serif)',
        secondary: 'var(--font-secondary, system-ui, sans-serif)',
      },
    },
  },
  plugins: [],
}

