import type { AppSettingsPublic } from '../api/settings';

export const mockPublicSettings: AppSettingsPublic = {
    site_name: 'Test Site',
    logo_base64: null,
    favicon_base64: null,
    color_primary: '#1976d2',
    color_secondary: '#dc004e',
    color_accent: '#9c27b0',
    color_background: '#ffffff',
    color_surface: '#f5f5f5',
    color_text_primary: '#000000',
    color_text_secondary: '#666666',
    color_success: '#4caf50',
    color_error: '#f44336',
    color_primary_dark: '#90caf9',
    color_secondary_dark: '#f48fb1',
    color_accent_dark: '#ce93d8',
    color_background_dark: '#121212',
    color_surface_dark: '#1e1e1e',
    color_text_primary_dark: '#e0e0e0',
    color_text_secondary_dark: '#b0b0b0',
    color_success_dark: '#81c784',
    color_error_dark: '#e57373',
    font_primary: 'Roboto, sans-serif',
    font_secondary: 'Roboto, sans-serif',
    footer_text: 'Test Footer',
    footer_links: [],
};
